### PR TITLE
task: improve responsive layout

### PR DESCRIPTION
**Pull request by resah**
improvements for people and articles sections

Refs: #15

Please check whether this is fine before merging, since CSS is not my strong point ;)

### CODE REVIEW

**Comment by hauptrolle** [comment]
@bastianccm Is it possible to deploy PR to some kind of preview branch? Otherwise it is quite hard to compare the visual changes ... 😁

**Comment by bastianccm** [comment]
Hey @resah can you push this to a branch in this repo instead of your fork? Then we'll get an automated deployment.
Unfortunately, we can not deploy previews from forks :(

**Comment by resah** [comment]
@bastianccm I would, but I tried yesterday and had no permission to do create/push a branch in this repository

**Comment by bastianccm** [comment]
@resah please check your mails, I invited you to the devteam :)

**Pull request closed without merging**
