### PR TITLE
task: adjust page style and structure to look like AOE website

### PR DESCRIPTION
**Pull request by resah**
Restructuring of the basic page to a look and feel similar to AOE website. 
Font, colors, gradients, some margins, ... on all pages and partials.

Refs: #16

### CODE REVIEW

**Comment by bastianccm** [comment]
Screenshot 2022-03-17 at 14 34 18

On a large screen this becomes very narrow, maybe we can make it wider like the aoe website?

**Comment by resah** [comment]
@bastianccm While you are absolutely right, the text content of the AOE website is as narrow. Only the page-wide header images break this. Since the opensource page itself has no header images we would have to break the defined content width. 
I would leave the decision to an expert @fbrandel :)

**Comment by fbrandel** [comment]
I also agree to increase the max-with of the container. 
The only thing to remember is to not increase the width of textual content to keep it readable. So the section "AOE Articles" and the article detail might stay a bit narrower, but the "AOE Projects" section is "full-width".

**Comment by resah** [comment]
Ok, I adjusted the container width.

**Review by bastianccm — APPROVED** [review]
I like that :)

**Pull request merged**
